version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 15
    funlen:
      lines: 100
      statements: 50
    gocognit:
      min-complexity: 15
    gocyclo:
      min-complexity: 15
    godot:
      scope: declarations
      exclude:
        - '^FIXME:'
        - '^fixme:'
        - '^TODO:'
        - '^todo:'
    gosec:
      excludes:
        - G204
    lll:
      line-length: 120
    misspell:
      locale: US
    mnd:
      ignored-functions:
        - args.Error
        - flag.Arg
        - flag.Duration
        - flag.Float64
        - flag.Int
        - flag.Int64
        - flag.String
        - flag.Uint
        - flag.Uint64
        - fmt.Errorf
        - fmt.Print
        - fmt.Printf
        - fmt.Println
        - fmt.Sprintf
        - fmt.Sprint
        - log.Print
        - log.Printf
        - log.Println
        - strconv.FormatFloat
        - strconv.FormatInt
        - strconv.FormatUint
        - strconv.ParseFloat
        - strconv.ParseInt
        - strconv.ParseUint
    nakedret:
      max-func-lines: 30
    varnamelen:
      min-name-length: 2
      ignore-names:
        - err
        - ok
        - i
        - j
        - k
        - v
        - id
        - ip
        - db
        - tx
        - up
        - to
        - in
        - ch
        - fn
        - fs
        - wg
        - mu
        - fd
        - st
        - sb
        - b
        - e
        - "n"
        - s
        - t
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
          - dupl
          - err113
          - errcheck
          - funlen
          - gocognit
          - gocyclo
          - gosec
          - ireturn
          - maintidx
          - nlreturn
          - testpackage
          - varnamelen
          - wrapcheck
          - wsl
        path: _test\.go
      - linters:
          - staticcheck
        text: 'S1002:'
      - linters:
          - revive
        text: 'package-comments:'
      - linters:
          - revive
        text: 'unused-parameter:'
      - linters:
          - gocritic
        text: 'unnecessaryDefer:'
      - linters:
          - err113
        text: do not compare errors directly
      - linters:
          - errorlint
        text: type assertion on error will fail on wrapped errors
      - linters:
          - ireturn
        text: returns generic interface
      - linters:
          - gocognit
        text: cognitive complexity .* of func `FilterByType`
      - linters:
          - tagliatelle
        text: json
      - linters:
          - forbidigo
        text: use of `fmt.Printf` forbidden
      - linters:
          - mnd
        text: 'Magic number: 3'
      - linters:
          - wrapcheck
        text: error returned from external package is unwrapped.*json.Marshal
      - linters:
          - godot
        path: _test\.go
      - linters:
          - revive
        text: var-declaration
      - linters:
          - gocritic
        text: ifElseChain
      - linters:
          - lll
        path: _test\.go
      - linters:
          - staticcheck
        text: should omit type.*from declaration
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
