name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25.x

    - name: Run tests
      run: go test -v ./...

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.4.0
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Run golangci-lint
      run: golangci-lint run --timeout=5m

    - name: Generate changelog
      id: changelog
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Generate changelog from git log since last tag
        PREV_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")
        if [ -n "$PREV_TAG" ]; then
          CHANGELOG=$(git log --pretty=format:"- %s" $PREV_TAG..HEAD)
        else
          CHANGELOG=$(git log --pretty=format:"- %s")
        fi
        
        # Create changelog file
        cat > CHANGELOG.md << EOF
        # Release $VERSION
        
        ## Changes
        $CHANGELOG
        
        ## Installation
        \`\`\`bash
        go get github.com/hacomono-lib/go-errorsx@$VERSION
        \`\`\`
        EOF
        
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        cat CHANGELOG.md >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Check if release exists
      id: check_release
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        RELEASE_EXISTS=$(gh release view $VERSION >/dev/null 2>&1 && echo "true" || echo "false")
        echo "exists=$RELEASE_EXISTS" >> $GITHUB_OUTPUT
        echo "Release $VERSION exists: $RELEASE_EXISTS"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      if: steps.check_release.outputs.exists == 'false'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.changelog.outputs.version }}
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false

    - name: Skip Release Creation
      if: steps.check_release.outputs.exists == 'true'
      run: |
        echo "Release ${{ steps.changelog.outputs.version }} already exists. Skipping creation."

    - name: Update pkg.go.dev
      run: |
        # Trigger pkg.go.dev to update the documentation
        curl -X POST "https://proxy.golang.org/github.com/hacomono-lib/go-errorsx/@v/${{ steps.changelog.outputs.version }}.info" || true